/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package datagen.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class purchase extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2730564248754946385L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"purchase\",\"namespace\":\"datagen.example\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"item_type\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"long\"},{\"name\":\"price_per_unit\",\"type\":{\"type\":\"bytes\",\"scale\":2,\"precision\":4,\"connect.version\":1,\"connect.parameters\":{\"scale\":\"2\",\"connect.decimal.precision\":\"4\"},\"connect.name\":\"org.apache.kafka.connect.data.Decimal\",\"logicalType\":\"decimal\"}}],\"connect.name\":\"datagen.example.purchase\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<purchase> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<purchase> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<purchase> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<purchase> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<purchase> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this purchase to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a purchase from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a purchase instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static purchase fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence item_type;
  private long quantity;
  private java.nio.ByteBuffer price_per_unit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public purchase() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param item_type The new value for item_type
   * @param quantity The new value for quantity
   * @param price_per_unit The new value for price_per_unit
   */
  public purchase(java.lang.Long id, java.lang.CharSequence item_type, java.lang.Long quantity, java.nio.ByteBuffer price_per_unit) {
    this.id = id;
    this.item_type = item_type;
    this.quantity = quantity;
    this.price_per_unit = price_per_unit;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return item_type;
    case 2: return quantity;
    case 3: return price_per_unit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: item_type = (java.lang.CharSequence)value$; break;
    case 2: quantity = (java.lang.Long)value$; break;
    case 3: price_per_unit = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'item_type' field.
   * @return The value of the 'item_type' field.
   */
  public java.lang.CharSequence getItemType() {
    return item_type;
  }


  /**
   * Sets the value of the 'item_type' field.
   * @param value the value to set.
   */
  public void setItemType(java.lang.CharSequence value) {
    this.item_type = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public long getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(long value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'price_per_unit' field.
   * @return The value of the 'price_per_unit' field.
   */
  public java.nio.ByteBuffer getPricePerUnit() {
    return price_per_unit;
  }


  /**
   * Sets the value of the 'price_per_unit' field.
   * @param value the value to set.
   */
  public void setPricePerUnit(java.nio.ByteBuffer value) {
    this.price_per_unit = value;
  }

  /**
   * Creates a new purchase RecordBuilder.
   * @return A new purchase RecordBuilder
   */
  public static datagen.example.purchase.Builder newBuilder() {
    return new datagen.example.purchase.Builder();
  }

  /**
   * Creates a new purchase RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new purchase RecordBuilder
   */
  public static datagen.example.purchase.Builder newBuilder(datagen.example.purchase.Builder other) {
    if (other == null) {
      return new datagen.example.purchase.Builder();
    } else {
      return new datagen.example.purchase.Builder(other);
    }
  }

  /**
   * Creates a new purchase RecordBuilder by copying an existing purchase instance.
   * @param other The existing instance to copy.
   * @return A new purchase RecordBuilder
   */
  public static datagen.example.purchase.Builder newBuilder(datagen.example.purchase other) {
    if (other == null) {
      return new datagen.example.purchase.Builder();
    } else {
      return new datagen.example.purchase.Builder(other);
    }
  }

  /**
   * RecordBuilder for purchase instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<purchase>
    implements org.apache.avro.data.RecordBuilder<purchase> {

    private long id;
    private java.lang.CharSequence item_type;
    private long quantity;
    private java.nio.ByteBuffer price_per_unit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(datagen.example.purchase.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.item_type)) {
        this.item_type = data().deepCopy(fields()[1].schema(), other.item_type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.price_per_unit)) {
        this.price_per_unit = data().deepCopy(fields()[3].schema(), other.price_per_unit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing purchase instance
     * @param other The existing instance to copy.
     */
    private Builder(datagen.example.purchase other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.item_type)) {
        this.item_type = data().deepCopy(fields()[1].schema(), other.item_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price_per_unit)) {
        this.price_per_unit = data().deepCopy(fields()[3].schema(), other.price_per_unit);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public datagen.example.purchase.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public datagen.example.purchase.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'item_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemType() {
      return item_type;
    }


    /**
      * Sets the value of the 'item_type' field.
      * @param value The value of 'item_type'.
      * @return This builder.
      */
    public datagen.example.purchase.Builder setItemType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.item_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'item_type' field has been set.
      * @return True if the 'item_type' field has been set, false otherwise.
      */
    public boolean hasItemType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'item_type' field.
      * @return This builder.
      */
    public datagen.example.purchase.Builder clearItemType() {
      item_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public long getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public datagen.example.purchase.Builder setQuantity(long value) {
      validate(fields()[2], value);
      this.quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public datagen.example.purchase.Builder clearQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'price_per_unit' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getPricePerUnit() {
      return price_per_unit;
    }


    /**
      * Sets the value of the 'price_per_unit' field.
      * @param value The value of 'price_per_unit'.
      * @return This builder.
      */
    public datagen.example.purchase.Builder setPricePerUnit(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.price_per_unit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'price_per_unit' field has been set.
      * @return True if the 'price_per_unit' field has been set, false otherwise.
      */
    public boolean hasPricePerUnit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'price_per_unit' field.
      * @return This builder.
      */
    public datagen.example.purchase.Builder clearPricePerUnit() {
      price_per_unit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public purchase build() {
      try {
        purchase record = new purchase();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.item_type = fieldSetFlags()[1] ? this.item_type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.quantity = fieldSetFlags()[2] ? this.quantity : (java.lang.Long) defaultValue(fields()[2]);
        record.price_per_unit = fieldSetFlags()[3] ? this.price_per_unit : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<purchase>
    WRITER$ = (org.apache.avro.io.DatumWriter<purchase>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<purchase>
    READER$ = (org.apache.avro.io.DatumReader<purchase>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










